### ISSUE TITLE
custom jwt token header name

### ISSUE THREAD

**Issue by gfrankliu** [IvanJosipovic/OIDC-Guard#27]
When the request comes in via the [Google Identity Aware Proxy (IAP)](https://cloud.google.com/iap/docs/signed-headers-howto), the IAP adds the jwt token using the header name `x-goog-iap-jwt-assertion`. Does OIDC-Guard support reading the jwt token from a custom header instead of the default `Authorization` header?

**Comment by IvanJosipovic** [comment]
Version 2.0.0 supports this:

```yaml
  JWT:
    # Sets Authorization header name, if not set "Authorization" will be used
    authorizationHeader: ""
```
