### ISSUE TITLE
jwks_uri

### ISSUE THREAD

**Issue by gfrankliu** [IvanJosipovic/OIDC-Guard#28]
Instead of using the auto discovery url OpenIdProviderConfigurationUrl , can we use jwks_uri directly? eg: `jwks_uri=https://login.microsoftonline.com/common/discovery/v2.0/keys` ?

This is followup to https://github.com/IvanJosipovic/OIDC-Guard/issues/27 where Google IAP only provides jwks URL https://www.gstatic.com/iap/verify/public_key-jwk

**Comment by IvanJosipovic** [comment]
Version 2.0.0 supports this:

Set

```yaml
  JWT:
    # Sets the JSON Web Key Set and ignores the openIdProviderConfigurationUrl
    # Make sure to set the validIssuers property
    JWKSUrl: ""
```
