### ISSUE TITLE
Redirect loop when user lacks required claim

### ISSUE THREAD

**Issue by neerax** [IvanJosipovic/OIDC-Guard#440]
With the following annotations:
```
annotations:
  nginx.ingress.kubernetes.io/auth-url: https://oidc-guard.default.svc.cluster.local/auth?groups=/app&inject-claim=preferred_username,preferred-username
  nginx.ingress.kubernetes.io/auth-signin: https://oidc-guard.example.org/signin
```
and helm values:

```
settings:
  logLeve: Debug
  openIdProviderConfigurationUrl: "https://keycloak.example.org/realms/MyOrganization/.well-known/openid-configuration"
  
  cookie:
    clientId: "oidc-guard"
    clientSecret: "***"
    cookieDomain: "example.org"
    host: oidc-guard.example.org
    scheme: https
ingress:
  enabled: true
  hosts:
    - host: oidc-guard.example.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - oidc-guard.example.org
```

when the user is autenticated but does not belongs to the /app group browser goes in an endless loop.

I haven't had time to investigate deeper, but it seems that oidc-guard returns a 401 in this case, which causes NGINX to trigger another authentication attempt.

It would be nice to implement a configuration option (e.g., an additional auth endpoint parameter) that allows redirecting the user to a custom page explaining that they are authenticated but not authorized.

Regards and thanks for you work.

**Comment by IvanJosipovic** [comment]
Hey, I'm on vacation at the moment, will look at this in the next few days.

**Comment by IvanJosipovic** [comment]
Hey,

I believe this is a limitation of nginx, at the moment `nginx.ingress.kubernetes.io/auth-signin` decides where the user is sent if they fail the auth test.

**Comment by IvanJosipovic** [comment]
Had some more thoughts about this. I'm thinking something like this could be possible.


```yaml
annotations:
  nginx.ingress.kubernetes.io/auth-url: https://oidc-guard.default.svc.cluster.local/auth?groups=/app&inject-claim=preferred_username,preferred-username
  nginx.ingress.kubernetes.io/auth-signin: https://oidc-guard.example.org/signin?groups=/app
```

If we add the same constraint to /signin?groups=/app, that page can programmatically check if the user is Unauthorized (display message) vs Unauthenticated (redirect to IDP).
